version: '3'
services:
  router:
    image: alpine
    privileged: true
    networks:
      net1:
        ipv4_address: 10.0.1.3
      net2:
        ipv4_address: 10.0.2.3
      net3:
        ipv4_address: 10.0.3.3
    cap_add:
      - NET_ADMIN
    command: sh -c "apk update && apk add --no-cache arptables && echo 1 > /proc/sys/net/ipv4/ip_forward && arptables -A FORWARD --match ether --ether-dst 00:00:00:00:00:00 -j DROP && sleep infinity"

  container1:
    image: alpine
    networks:
      net1:
        ipv4_address: 10.0.1.2

  container2:
    image: alpine
    networks:
      net2:
        ipv4_address: 10.0.2.2

  container3:
    image: alpine
    networks:
      net3:
        ipv4_address: 10.0.3.2
        
networks:
  net1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.3
  net2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.3
  net3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24
          gateway: 10.0.3.3
